# LAB Active Directory - 01-Load-LAB-Helpers.ps1
$ErrorActionPreference="Stop"
Import-Module ActiveDirectory -ErrorAction Stop
Import-Module GroupPolicy -ErrorAction Stop
function Ensure-ADOU { param([string]$Name,[string]$Path,[string]$Description="LAB OU")
 $DN="OU=$Name,$Path"; if(-not(Get-ADOrganizationalUnit -LDAPFilter "(distinguishedName=$DN)" -ErrorAction SilentlyContinue)){New-ADOrganizationalUnit -Name $Name -Path $Path -Description $Description -ProtectedFromAccidentalDeletion $true; Write-Host "[OK] OU $DN" -ForegroundColor Green}else{Write-Host "[SKIP] OU $DN" -ForegroundColor Yellow}}
function Ensure-ADGroup { param([string]$Name,[string]$Path,[ValidateSet('Global','DomainLocal','Universal')][string]$Scope,[string]$Description="LAB group")
 if(-not(Get-ADGroup -LDAPFilter "(sAMAccountName=$Name)" -ErrorAction SilentlyContinue)){New-ADGroup -Name $Name -SamAccountName $Name -GroupCategory Security -GroupScope $Scope -Path $Path -Description $Description; Write-Host "[OK] Group $Name" -ForegroundColor Green}else{Write-Host "[SKIP] Group $Name" -ForegroundColor Yellow}}
function Ensure-ADGroupMember { param([string]$Group,[string[]]$Members)
 foreach($M in $Members){$Obj=Get-ADObject -LDAPFilter "(|(sAMAccountName=$M)(name=$M))" -ErrorAction SilentlyContinue; if(-not $Obj){Write-Warning "Missing member $M"; continue}; $Exists=Get-ADGroupMember $Group -Recursive -ErrorAction Stop|? DistinguishedName -eq $Obj.DistinguishedName; if(-not $Exists){Add-ADGroupMember $Group $Obj.DistinguishedName; Write-Host "[OK] $M -> $Group" -ForegroundColor Green}else{Write-Host "[SKIP] $M -> $Group" -ForegroundColor Yellow}}}
function Ensure-ADUserLab { param([string]$SamAccountName,[string]$GivenName,[string]$Surname,[string]$Path,[securestring]$Password,[string]$Description="LAB user",[bool]$Enabled=$true,[bool]$PasswordNeverExpires=$false,[bool]$AccountNotDelegated=$false)
 if(-not(Get-ADUser -LDAPFilter "(sAMAccountName=$SamAccountName)" -ErrorAction SilentlyContinue)){ $Display="$GivenName $Surname"; New-ADUser -Name $Display -GivenName $GivenName -Surname $Surname -DisplayName $Display -SamAccountName $SamAccountName -UserPrincipalName "$SamAccountName@$Global:DomainDNS" -Path $Path -AccountPassword $Password -Enabled $Enabled -Description $Description; Write-Host "[OK] User $SamAccountName" -ForegroundColor Green}else{Write-Host "[SKIP] User $SamAccountName" -ForegroundColor Yellow}; Set-ADUser $SamAccountName -Description $Description -AccountNotDelegated:$AccountNotDelegated; if($PasswordNeverExpires){Set-ADUser $SamAccountName -PasswordNeverExpires $true}}
function Ensure-GPOWithLink { param([string]$Name,[string]$TargetDN,[string]$Comment="LAB GPO")
 if(-not(Get-GPO -Name $Name -ErrorAction SilentlyContinue)){New-GPO -Name $Name -Comment $Comment|Out-Null; Write-Host "[OK] GPO $Name" -ForegroundColor Green}else{Write-Host "[SKIP] GPO $Name" -ForegroundColor Yellow}; $L=(Get-GPInheritance -Target $TargetDN).GpoLinks|? DisplayName -eq $Name; if(-not $L){New-GPLink -Name $Name -Target $TargetDN -LinkEnabled Yes|Out-Null; Write-Host "[OK] Link $Name" -ForegroundColor Green}}
Write-Host "[OK] Helpers loaded" -ForegroundColor Green
