$ErrorActionPreference="Stop"; $ScriptRoot="C:\LAB-AD\Scripts"; if(-not $Global:LabDN){& "$ScriptRoot\00-Init-LAB-Session.ps1"}; if(-not(Get-Command Ensure-ADGroupMember -ErrorAction SilentlyContinue)){. "$ScriptRoot\01-Load-LAB-Helpers.ps1"}; if(-not $Global:LabUsers){& "$ScriptRoot\04-Create-LAB-Users.ps1"}
foreach($u in $LabUsers){Ensure-ADGroupMember "GG_LAB_AllUsers" @($u.Sam); if($u.Type -eq 'Department'){Ensure-ADGroupMember "GG_$($u.Unit)_Users" @($u.Sam)}; if($u.Director){Ensure-ADGroupMember "GG_LAB_Directors" @($u.Sam); Ensure-ADGroupMember "GG_$($u.Unit)_Director" @($u.Sam)}; if($u.Board){Ensure-ADGroupMember "GG_Board_Members" @($u.Sam)}}
foreach($s in @("it.user01","it.user02","it.user03","it.user04")){Ensure-ADGroupMember "GG_LAB_Admins" @("admin.$s")}
Ensure-ADGroupMember "GG_LAB_BreakGlass" @("super.user"); Ensure-ADGroupMember "Domain Admins" @("super.user"); Ensure-ADGroupMember "GG_LAB_HoneyObjects" @("admin.backup")
Ensure-ADGroupMember "GG_LAB_ServiceAccounts" @("svc.securityapp"); Ensure-ADGroupMember "GG_SecurityApp" @("svc.securityapp")
Ensure-ADGroupMember "DL_FS_Shared_RO" @("GG_LAB_AllUsers"); Ensure-ADGroupMember "DL_FS_Shared_FC" @("GG_LAB_Admins","GG_LAB_BreakGlass")
foreach($d in $Departments){Ensure-ADGroupMember "DL_FS_${d}_Public_WO" @("GG_${d}_Users"); Ensure-ADGroupMember "DL_FS_${d}_Public_RO" @("GG_${d}_Users"); Ensure-ADGroupMember "DL_FS_${d}_Public_MD" @("GG_${d}_Director","GG_SecurityApp"); Ensure-ADGroupMember "DL_FS_${d}_Public_FC" @("GG_LAB_Admins","GG_LAB_BreakGlass"); Ensure-ADGroupMember "DL_FS_${d}_Internal_MD" @("GG_${d}_Users","GG_${d}_Director","GG_SecurityApp"); Ensure-ADGroupMember "DL_FS_${d}_Internal_FC" @("GG_LAB_Admins","GG_LAB_BreakGlass"); Ensure-ADGroupMember "DL_FS_${d}_Confidential_MD" @("GG_${d}_Director","GG_Board_Members","GG_SecurityApp"); Ensure-ADGroupMember "DL_FS_${d}_Confidential_FC" @("GG_LAB_BreakGlass")}
Ensure-ADGroupMember "DL_FS_Governance_BoardOnly_MD" @("GG_Board_Members","GG_SecurityApp"); Ensure-ADGroupMember "DL_FS_Governance_BoardOnly_FC" @("GG_LAB_BreakGlass"); Ensure-ADGroupMember "DL_FS_Governance_BoardDirectors_MD" @("GG_Board_Members","GG_LAB_Directors","GG_SecurityApp"); Ensure-ADGroupMember "DL_FS_Governance_BoardDirectors_FC" @("GG_LAB_BreakGlass")
Ensure-ADGroupMember "DL_RDP_SRV-FS-001_Admins" @("GG_LAB_Admins","GG_LAB_BreakGlass"); Ensure-ADGroupMember "DL_RDP_SRV-APP-001_Admins" @("GG_LAB_Admins","GG_LAB_BreakGlass"); Ensure-ADGroupMember "DL_RDP_SRV-DB-001_Admins" @("GG_LAB_Admins","GG_LAB_BreakGlass")
Write-Host "[OK] Memberships complete" -ForegroundColor Green
