$ErrorActionPreference="Stop"; Import-Module ActiveDirectory; Import-Module GroupPolicy; Import-Module NetSecurity
$D=Get-ADDomain; $DomainDN=$D.DistinguishedName; $DomainDNS=$D.DNSRoot; $LabDN="OU=LAB,$DomainDN"; $LabSubnet="10.0.0.0/24"; $DCAddress="10.0.0.1"; $AdminRemoteAddresses=@("10.0.0.100")
function G($n,$target){if(-not(Get-GPO -Name $n -ErrorAction SilentlyContinue)){New-GPO -Name $n|Out-Null}; if(-not((Get-GPInheritance $target).GpoLinks|? DisplayName -eq $n)){New-GPLink -Name $n -Target $target -LinkEnabled Yes|Out-Null}; $n}
function Store($g){"$DomainDNS\$g"}
function Base($g){Set-NetFirewallProfile -PolicyStore (Store $g) -Profile Domain,Private,Public -Enabled True -DefaultInboundAction Block -DefaultOutboundAction Allow}
function FR($g,$n,$proto,$port,$remote){$ps=Store $g; $e=Get-NetFirewallRule -PolicyStore $ps -DisplayName $n -ErrorAction SilentlyContinue; if($e){$e|Remove-NetFirewallRule}; New-NetFirewallRule -PolicyStore $ps -DisplayName $n -Direction Inbound -Action Allow -Protocol $proto -LocalPort $port -RemoteAddress $remote -Profile Any|Out-Null}
function ICMP($g,$n,$remote){$ps=Store $g; $e=Get-NetFirewallRule -PolicyStore $ps -DisplayName $n -ErrorAction SilentlyContinue; if($e){$e|Remove-NetFirewallRule}; New-NetFirewallRule -PolicyStore $ps -DisplayName $n -Protocol ICMPv4 -IcmpType 8 -Direction Inbound -Action Allow -RemoteAddress $remote -Profile Any|Out-Null}
$GDC=G "GPO-LAB-DomainControllers-Firewall" "OU=Domain Controllers,$DomainDN"; $GWS=G "GPO-LAB-Workstations-Firewall" "OU=Workstations,OU=Computers,$LabDN"; $GFS=G "GPO-LAB-FileServers-Firewall" "OU=FileServers,OU=Servers,OU=Computers,$LabDN"; $GAPP=G "GPO-LAB-AppServers-Firewall" "OU=AppServers,OU=Servers,OU=Computers,$LabDN"; $GDB=G "GPO-LAB-DBServers-Firewall" "OU=DBServers,OU=Servers,OU=Computers,$LabDN"; $GSTG=G "GPO-LAB-Staging-Firewall" "OU=Staging,OU=Computers,$LabDN"
foreach($g in @($GDC,$GWS,$GFS,$GAPP,$GDB,$GSTG)){Base $g}
foreach($r in @(@('UDP',53),@('TCP',53),@('TCP',88),@('UDP',88),@('TCP',389),@('UDP',389),@('TCP',445),@('TCP',135),@('UDP',123),@('TCP',3268))){FR $GDC "LAB-DC-Allow-$($r[0])-$($r[1])-From-Lab" $r[0] $r[1] @($LabSubnet)}; FR $GDC "LAB-DC-Allow-RDP-3389-From-AdminSources" TCP 3389 $AdminRemoteAddresses; ICMP $GDC "LAB-DC-Allow-ICMPv4-From-Lab" @($LabSubnet)
FR $GWS "LAB-WS-Allow-WinRM-5985-From-DC01" TCP 5985 @($DCAddress); ICMP $GWS "LAB-WS-Allow-ICMPv4-From-Lab" @($LabSubnet)
FR $GFS "LAB-FS-Allow-SMB-445-From-Lab" TCP 445 @($LabSubnet); FR $GFS "LAB-FS-Allow-WinRM-5985-From-DC01" TCP 5985 @($DCAddress); FR $GFS "LAB-FS-Allow-RDP-3389-From-AdminSources" TCP 3389 $AdminRemoteAddresses; ICMP $GFS "LAB-FS-Allow-ICMPv4-From-Lab" @($LabSubnet)
foreach($g in @($GAPP,$GDB)){FR $g "LAB-Allow-WinRM-5985-From-DC01" TCP 5985 @($DCAddress); FR $g "LAB-Allow-RDP-3389-From-AdminSources" TCP 3389 $AdminRemoteAddresses; ICMP $g "LAB-Allow-ICMPv4-From-Lab" @($LabSubnet)}; ICMP $GSTG "LAB-STG-Allow-ICMPv4-From-Lab" @($LabSubnet)
Write-Host "[OK] Firewall GPOs complete" -ForegroundColor Green
