$ErrorActionPreference="Stop"; Import-Module ActiveDirectory; Import-Module GroupPolicy
$D=Get-ADDomain; $DomainDN=$D.DistinguishedName; $DomainDNS=$D.DNSRoot; $LabDN="OU=LAB,$DomainDN"; $Departments=@("IT","Finance","HR","Marketing","Sales"); $WallpaperDir="\\$DomainDNS\SYSVOL\$DomainDNS\scripts\Wallpapers"; New-Item $WallpaperDir -ItemType Directory -Force|Out-Null
function G($n,$target){if(-not(Get-GPO -Name $n -ErrorAction SilentlyContinue)){New-GPO -Name $n|Out-Null}; if(-not((Get-GPInheritance $target).GpoLinks|? DisplayName -eq $n)){New-GPLink -Name $n -Target $target -LinkEnabled Yes|Out-Null}; $n}
function Filter($g,$grp){Set-GPPermission -Name $g -TargetName "Authenticated Users" -TargetType Group -PermissionLevel GpoRead -ErrorAction SilentlyContinue|Out-Null; Set-GPPermission -Name $g -TargetName $grp -TargetType Group -PermissionLevel GpoApply|Out-Null}
function Reg($g,$k,$v,$t,$val){Set-GPRegistryValue -Name $g -Key $k -ValueName $v -Type $t -Value $val}
function Lock($g,$sec){Reg $g "HKCU\Software\Policies\Microsoft\Windows\Control Panel\Desktop" ScreenSaveActive String "1"; Reg $g "HKCU\Software\Policies\Microsoft\Windows\Control Panel\Desktop" ScreenSaverIsSecure String "1"; Reg $g "HKCU\Software\Policies\Microsoft\Windows\Control Panel\Desktop" ScreenSaveTimeOut String $sec}
function WP($g,$p){Reg $g "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\System" Wallpaper String $p; Reg $g "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\System" WallpaperStyle String "2"; Reg $g "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\ActiveDesktop" NoChangingWallPaper DWord 1}
function USBOff($g){Reg $g "HKCU\Software\Policies\Microsoft\Windows\RemovableStorageDevices" Deny_All DWord 1}; function AutorunOff($g){Reg $g "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" NoDriveTypeAutoRun DWord 255}
function BlockApps($g){$base="HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer"; Reg $g $base DisallowRun DWord 1; $i=1; foreach($a in @("powershell.exe","powershell_ise.exe","pwsh.exe","cmd.exe","regedit.exe","mmc.exe","wscript.exe","cscript.exe","mshta.exe")){Reg $g "$base\DisallowRun" ([string]$i) String $a; $i++}}
function FGPP($name,$group,$prec,$len){try{$e=Get-ADFineGrainedPasswordPolicy $name -ErrorAction Stop}catch{$e=$null}; if(-not $e){New-ADFineGrainedPasswordPolicy -Name $name -Precedence $prec -ComplexityEnabled $true -ReversibleEncryptionEnabled $false -MinPasswordLength $len -PasswordHistoryCount 24 -MaxPasswordAge "60.00:00:00" -MinPasswordAge "1.00:00:00" -LockoutThreshold 5 -LockoutDuration "00:30:00" -LockoutObservationWindow "00:30:00"}else{Set-ADFineGrainedPasswordPolicy -Identity $name -Precedence $prec -MinPasswordLength $len -ComplexityEnabled $true}; if(-not(Get-ADFineGrainedPasswordPolicySubject $name|? Name -eq $group)){Add-ADFineGrainedPasswordPolicySubject $name -Subjects $group}}
function MkBmp($path,$title){ if(Test-Path $path){return}; Add-Type -AssemblyName System.Drawing; $b=New-Object Drawing.Bitmap 1200,700; $g=[Drawing.Graphics]::FromImage($b); $g.Clear([Drawing.Color]::DarkSlateBlue); $brush=[Drawing.Brushes]::White; $font=New-Object Drawing.Font("Segoe UI",42,[Drawing.FontStyle]::Bold); $g.DrawString($title,$font,$brush,50,280); $b.Save($path,[Drawing.Imaging.ImageFormat]::Bmp); $g.Dispose(); $b.Dispose() }
foreach($dpt in $Departments){MkBmp "$WallpaperDir\LAB-$dpt-Users.bmp" "LAB $dpt Users"; MkBmp "$WallpaperDir\LAB-$dpt-Director.bmp" "LAB $dpt Director"; $ou="OU=$dpt,OU=Departments,$LabDN"; $gb=G "GPO-LAB-$dpt-BaseUsers" $ou; $gd=G "GPO-LAB-$dpt-Directors" $ou; Filter $gb "GG_${dpt}_Users"; Filter $gd "GG_${dpt}_Director"; Lock $gb "900"; WP $gb "$WallpaperDir\LAB-$dpt-Users.bmp"; AutorunOff $gb; USBOff $gb; BlockApps $gb; Lock $gd "600"; WP $gd "$WallpaperDir\LAB-$dpt-Director.bmp"; AutorunOff $gd; USBOff $gd; BlockApps $gd}
foreach($x in @("Governance-Board","Admins","BreakGlass","HoneyObjects","ServiceAccounts")){MkBmp "$WallpaperDir\LAB-$x.bmp" "LAB $x"}
$gg=G "GPO-LAB-Governance-Users" "OU=Governance,$LabDN"; Lock $gg "600"; WP $gg "$WallpaperDir\LAB-Governance-Board.bmp"; AutorunOff $gg; USBOff $gg; BlockApps $gg
$ga=G "GPO-LAB-Admins-Restrictions" "OU=IT-Admins,OU=Admins,$LabDN"; Lock $ga "300"; WP $ga "$WallpaperDir\LAB-Admins.bmp"; AutorunOff $ga
$gbg=G "GPO-LAB-BreakGlass-Minimal" "OU=Break-Glass,OU=Admins,$LabDN"; Lock $gbg "300"; WP $gbg "$WallpaperDir\LAB-BreakGlass.bmp"; AutorunOff $gbg
$gh=G "GPO-LAB-HoneyObjects-Restrictions" "OU=Honey-Objects,OU=Admins,$LabDN"; Lock $gh "300"; WP $gh "$WallpaperDir\LAB-HoneyObjects.bmp"; AutorunOff $gh; USBOff $gh; BlockApps $gh
$gs=G "GPO-LAB-ServiceAccounts-Restrictions" "OU=ServiceAccounts,$LabDN"; Lock $gs "300"; WP $gs "$WallpaperDir\LAB-ServiceAccounts.bmp"; AutorunOff $gs; USBOff $gs; BlockApps $gs
FGPP "FGPP-LAB-Admins-StrongPassword" "GG_LAB_Admins" 10 16; FGPP "FGPP-LAB-Board-StrongPassword" "GG_Board_Members" 20 14
Write-Host "[OK] User class GPOs complete" -ForegroundColor Green
